name: google_maps_cluster_manager
description: Simple Flutter clustering library for Google Maps based on Geohash.
version: 3.0.0+1
homepage: https://github.com/bpillon/google_maps_cluster_manager

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter_platform_interface:
      git:
        url: https://github.com/danyialkhan/packages.git
        path: packages/google_maps_flutter/google_maps_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
